Chore: OpenAI API 설정
team-sticky-252/readim-client pull request #18
Opened 2024-06-26 17:30 UTC by dlgnswk

## 개요
가져온 DOM 본문을 OpenAI API를 호출해 요약된 내용을 받아오기 위한 기본설정을 작업했습니다.

## 코드 변경 사항
- 생성형 ai model 설정, max token 수 설정, 기본 prompt 명령 설정했습니다.
- api key 를 .env 파일에 생성하였습니다.
- api 호출시 오류 발생하는 경우 `console.error()` 를 호출하도록 했습니다.

## 기타 전달 사항
- 추후 에러처리 작성시 `console.error()` 제거 후 로직 작성하시면 됩니다.

## PR Checklist

- [x] 주어진 Task의 요구사항을 모두 작성했습니다.
- [x] 작성한 PR을 다시 한번 더 검토하였습니다.
- [x] merge 할 브랜치의 위치를 확인하였습니다.

2024-06-26 17:36 UTC, JieunZoeyOh requested changes
재훈님 고생하셨습니다!

2024-06-26 17:36 UTC, JieunZoeyOh commented on src/utils/api.js
> +const opnaikey = import.meta.env.VITE_OPENAI_API_KEY;
```suggestion
const OPENAI_API_KEY = import.meta.env.VITE_OPENAI_API_KEY;
```
상수화 하면 좋을 것 같습니다!

2024-06-27 02:03 UTC, Pangho04 approved these changes
고생하셨습니다!

2024-06-27 02:51 UTC, JieunZoeyOh approved these changes

2024-06-27 02:54 UTC, merged