Feat: Summary 컴포넌트 UI 및 기능 변경
team-sticky-252/readim-client pull request #37
Opened 2024-06-30 20:14 UTC by dlgnswk

## 개요
테스터의 의견을 반영하여 Summary 컴포넌트 UI의 수정 요청사항을 반영하고 기능을 추가하였습니다.

## 코드 변경 사항
- 생성된 컴포넌트에 저장된 ref와 클릭한 곳이 다른 경우 닫히는 함수를 실행합니다.
https://github.com/team-sticky-252/readim-client/blob/d427fe4282a5dd981f4fe2a12caca6e0cfb4134e/src/components/Summary/Summary.jsx#L67-L71

## 기타 전달 사항
- X

## PR Checklist
- [x] 주어진 Task의 요구사항을 모두 작성했습니다.
- [x] 작성한 PR을 다시 한번 더 검토하였습니다.
- [x] merge 할 브랜치의 위치를 확인하였습니다.

2024-06-30 20:36 UTC, JieunZoeyOh requested changes
재훈님 고생하셨습니다! 코멘트 확인 부탁드릴게요.

2024-06-30 20:36 UTC, JieunZoeyOh commented on src/components/Summary/Summary.jsx
> +    };
```suggestion

```
불필요한 코드 같습니다.

2024-06-30 20:36 UTC, JieunZoeyOh commented on src/components/Summary/SummaryMessage.jsx
> +    <div className="px-5 py-3 mt-2 font-normal text-white break-all ext-base max-w-96 rounded-xl bg-pan-left bg-gradient-to-r from-pastel-purple via-blush-pink to-sunset-orange">
```suggestion
    <div className="px-5 py-3 mt-2 font-normal text-white break-all text-base max-w-96 rounded-xl bg-pan-left bg-gradient-to-r from-pastel-purple via-blush-pink to-sunset-orange">
```

오타인 것 같습니다.

2024-07-01 02:19 UTC, Pangho04 requested changes
코멘트 확인 부탁드립니다!

2024-07-01 02:19 UTC, Pangho04 commented on src/components/Summary/Summary.jsx
> +  const handleCloseSummaryClick = () => {
현재 바깥을 클릭하면 사라지는 애니메이션만 재생되고, 컴포넌트 자체는 화면에 유지되는 것 같습니다!
이로 인해,
 "바깥 클릭으로 인해 Summary 창 사라짐 -> 눈에만 보이지 않게됨(존재함) -> 뒤쪽이 여전히 클릭 등 상호작용되지 않음"
상태입니다! 수정 부탁드립니다~

2024-07-01 02:19 UTC, Pangho04 commented on src/components/Summary/Summary.jsx
> +      if (summaryRef.current && !summaryRef.current.contains(event.target)) {
```
 if (!summaryRef.current.contains(event.target))
```
로 작성해도 동작하는 것 같습니다!

2024-07-01 05:15 UTC, Pangho04 approved these changes
고생하셨습니다~!

2024-07-01 05:17 UTC, JieunZoeyOh approved these changes

2024-07-01 05:18 UTC, merged