Test: Welcome, InfoConceptText, ToastContainer 컴포넌트 테스트 코드 추가
team-sticky-252/readim-client pull request #51
Opened 2024-07-05 14:47 UTC by Pangho04

## 개요

#57

1. Test: `<Welcome>`, `<InfoConceptText>`, `<ToastContainer>` 컴포넌트 테스트 코드를 추가하였습니다.
2. `<ToastContainer>` 컴포넌트 내의 `handleDeleteAllMessageClick()`의 사용되지 않는 `clearTimeout()`을 삭제했습니다.

## 코드 변경 사항

### 1. 테스트 코드 추가 사항
  - `<Welcome>` :
    - `<InfoConceptText>`의 순환여부. 
  - `<ToastContainer>` : 
    - `MessageList` 표시 여부.
    -`deleteAllMessages()` 작동 여부.

### 2. <ToastContainer /> -> `handleDeleteAllMessageClick()` 내의 `clearTimeout()` 삭제.
https://github.com/team-sticky-252/readim-client/blob/4899316971845fa01656959d6512e98210cea3b6/src/components/Toast/ToastContainer.jsx#L10-L21

## 기타 전달 사항

## PR Checklist

- [x] 주어진 Task의 요구사항을 모두 작성했습니다.
- [x] 작성한 PR을 다시 한번 더 검토하였습니다.
- [x] merge 할 브랜치의 위치를 확인하였습니다.

2024-07-05 15:36 UTC, JieunZoeyOh approved these changes
고생하셨습니다.

2024-07-05 15:36 UTC, JieunZoeyOh commented on src/spec/ToastContainer.spec.jsx
> +import { act } from "react";
```suggestion
import { act } from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";

import ToastContainer from "../components/Toast/ToastContainer";
```
라이브러리와 컴포넌트를 구분하면 좋을 것 같습니다.

2024-07-05 15:36 UTC, JieunZoeyOh commented on src/spec/ToastContainer.spec.jsx
> +      vi.advanceTimersByTime(1500);
테스트 설명인 0.5초와 맞추면 좋을 것 같아요!

2024-07-05 16:10 UTC, Pangho04 commented on src/spec/ToastContainer.spec.jsx
> +import { act } from "react";
수정했습니다!

2024-07-05 16:11 UTC, Pangho04 commented on src/spec/ToastContainer.spec.jsx
> +      vi.advanceTimersByTime(1500);
ToastMessage 컴포넌트의 단일 토스트 메시지 삭제 함수와의 통일성을 위해 모든 토스트 메시지 함수의 setTimeout을 500ms로 수정하였습니다.

2024-07-06 01:35 UTC, dlgnswk requested changes
코멘트 확인 부탁드립니다!

2024-07-06 01:35 UTC, dlgnswk commented on src/spec/ToastContainer.spec.jsx
> +    const deleteAllbutton = screen.getByText("모두 지우기").parentElement;
```suggestion
    const deleteAllButton = screen.getByText("모두 지우기").parentElement;
```
카멜 케이스 적용 부탁드립니다!

2024-07-06 01:54 UTC, Pangho04 commented on src/spec/ToastContainer.spec.jsx
> +    const deleteAllbutton = screen.getByText("모두 지우기").parentElement;
적용 완료했습니다

2024-07-06 02:05 UTC, dlgnswk approved these changes
고생 많으셨습니다!

2024-07-06 02:07 UTC, merged